export const MODULES_FETCHING = "MODULES_FETCHING";
export const MODULES_FETCHING_DONE = "MODULES_FETCHING_DONE";
export const MODULES_FETCHING_ERROR = "MODULES_FETCHING_ERROR";

export const MODULE_CREATE = "MODULE_CREATE";
export const MODULE_CREATE_DONE = "MODULE_CREATE_DONE";
export const MODULE_CREATE_ERROR = "MODULE_CREATE_ERROR";

export const MODULE_UPDATE = "MODULE_UPDATE";
export const MODULE_UPDATE_DONE = "MODULE_UPDATE_DONE";
export const MODULE_UPDATE_ERROR = "MODULE_UPDATE_ERROR";

export const MODULE_DELETE = "MODULE_DELETE";
export const MODULE_DELETE_DONE = "MODULE_DELETE_DONE";
export const MODULE_DELETE_ERROR = "MODULE_DELETE_ERROR";

export const FETCH_APP = "FETCH_APP";
export const FETCH_APP_DONE = "FETCH_APP_DONE";
export const FETCH_APP_ERROR = "FETCH_APP_ERROR";

export const MODULE_PUBLISH = "MODULE_PUBLISH";
export const MODULE_PUBLISH_DONE = "MODULE_PUBLISH_DONE";
export const MODULE_PUBLISH_ERROR = "MODULE_PUBLISH_ERROR";
