export const SET_ACTIVE_APP = "SET_ACTIVE_APP";
export const SET_CODE = "SET_CODE";
export const RESET_CONFIG = "RESET";

export const SET_REVIEW_MODULE = "SET_REVIEW_MODULE";
export const SET_REVIEW_FILE = "SET_REVIEW_FILE";
export const SET_REVIEW_FILE_DATA = "SET_REVIEW_FILE_DATA";
export const RESET_REVIEW_FILE = "RESET_REVIEW_FILE";
export const RESET_REVIEW_FILE_DATA = "RESET_REVIEW_FILE_DATA";
export const RESET_CODE_REVIEW = "RESET_CODE_REVIEW";
