export const FETCH_TEST_CASES = 'FETCH_TEST_CASES';
export const FETCH_TEST_CASES_DONE = 'FETCH_TEST_CASES_DONE';
export const FETCH_TEST_CASES_ERROR = 'FETCH_TEST_CASES_ERROR';

export const CREATE_TEST_CASE = 'CREATE_TEST_CASE';
export const CREATE_TEST_CASE_DONE = 'CREATE_TEST_CASE_DONE';
export const CREATE_TEST_CASE_ERROR = 'CREATE_TEST_CASE_ERROR';

export const UPDATE_TEST_CASE = 'UPDATE_TEST_CASE';
export const UPDATE_TEST_CASE_DONE = 'UPDATE_TEST_CASE_DONE';
export const UPDATE_TEST_CASE_ERROR = 'UPDATE_TEST_CASE_ERROR';

export const DELETE_TEST_CASE = 'DELETE_TEST_CASE';
export const DELETE_TEST_CASE_DONE = 'DELETE_TEST_CASE_DONE';
export const DELETE_TEST_CASE_ERROR = 'DELETE_TEST_CASE_ERROR';

export const PUBLISH_TEST_CASES = 'PUBLISH_TEST_CASES';
export const PUBLISH_TEST_CASES_DONE = 'PUBLISH_TEST_CASES_DONE';
export const PUBLISH_TEST_CASES_ERROR = 'PUBLISH_TEST_CASES_ERROR';

export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_STATS_DONE = 'FETCH_STATS_DONE';
export const FETCH_STATS_ERROR = 'FETCH_STATS_ERROR';

export const CLEAR_TESTCASES = 'CLEAR_TESTCASES';