// MOVED TO PARENT TYPES

export const SORT_OLDEST = "SORT_OLDEST";
export const SORT_NEWEST = "SORT_NEWEST";
export const FILTER_TIMELINE = "FILTER_TIMELINE";
export const FILTER_CREATED_DATE = "FILTER_CREATED_DATE";
export const FILTER_TEAM_MEMBERS = "FILTER_TEAM_MEMBERS";
export const FILTER_SKILLS = "FILTER_SKILLS";
