export const FETCH_KANBAN_LIST = 'FETCH_KANBAN_LIST';
export const CREATE_KANBAN_LIST = 'CREATE_KANBAN_LIST';
export const UPDATE_KANBAN_LIST = 'UPDATE_KANBAN_LIST';
export const UPDATE_KANBAN_FILTER = 'UPDATE_KANBAN_FILTER';